### ISSUE TITLE
Scope of new compiled words should be in their Type Context dictionary rather than global.

### ISSUE THREAD

**Issue by scherrey** [ActorForth/ActorForth#5]
Presently all words are compiled to the global "Any" namespace. 

Going forward, new words should be compiled into the namespace that is presently the Type at tos(). If the stack is empty then the word will be compiled into the global namespace.

Can likely do this as part of the compiler refactor https://github.com/scherrey/ActorForth/issues/6

**Comment by SuperCipher** [comment]
#20 
Need to add test
test for the following type sig in test_types.py

- [x] [ [Tinput, Tinput, Tinput] -> [Toutput, Toutput] ]
- [x] [ [] -> [Toutput, Toutput] ]
- [x] [ [] -> [] ]

- [x] And test execute code for this issue make sure it put the type in the dictionary they belong.
